// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using atlas_the_public_think_tank.Data;

#nullable disable

namespace atlas_the_public_think_tank.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521133422_solution-subissue")]
    partial class solutionsubissue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a61454c-5b83-4aab-8661-96d6dffbee30"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Email = "whoLetTheDogsOut@barker.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "WHOLETTHEDOGSOUT@BARKER.COM",
                            NormalizedUserName = "COOPER.BARKER",
                            PasswordHash = "AQAAAAEAACcQAAAAEExamplePasswordHash==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d12ef04d-5b83-4aab-8661-567ffb12e15",
                            TwoFactorEnabled = false,
                            UserName = "Cooper.Barker"
                        },
                        new
                        {
                            Id = new Guid("1a61454c-5b83-4aab-8661-96d6dffbee31"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1b2c3e4-e5f6-7890-acsd-ef1234567891",
                            Email = "amelia.knight@example.org",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "AMELIA.KNIGHT@EXAMPLE.ORG",
                            NormalizedUserName = "AMELIA.KNIGHT",
                            PasswordHash = "AQAAAAEAACcQAAAAEExamplePasswordHash==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d12ef04d-5b83-4aab-8661-567ffb12e11",
                            TwoFactorEnabled = false,
                            UserName = "amelia.knight"
                        });
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.BlockedContent", b =>
                {
                    b.Property<Guid>("BlockedContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short?>("ReasonID")
                        .HasColumnType("smallint");

                    b.HasKey("BlockedContentID");

                    b.ToTable("BlockedContent", "app");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories", "app");

                    b.HasData(
                        new
                        {
                            CategoryID = new Guid("81f910e0-39a4-4b44-88ca-fd3c30af4a25"),
                            CategoryName = "Global Cooperation"
                        },
                        new
                        {
                            CategoryID = new Guid("25487e1f-b167-4666-a20c-dec2e4b5f413"),
                            CategoryName = "Sustainable Development"
                        },
                        new
                        {
                            CategoryID = new Guid("a8fb4691-8c1f-4e7d-b315-b042097e6395"),
                            CategoryName = "Equitable Access"
                        },
                        new
                        {
                            CategoryID = new Guid("f5c35e6a-8c4f-4556-b6c1-4448b26d1bcb"),
                            CategoryName = "Innovation and Technology"
                        },
                        new
                        {
                            CategoryID = new Guid("26c867f2-48c6-4bd5-b36a-9f7325431ad3"),
                            CategoryName = "Effective Governance"
                        },
                        new
                        {
                            CategoryID = new Guid("d2c7a605-a621-4b14-8d51-e2df0cecae1a"),
                            CategoryName = "Education and Awareness"
                        },
                        new
                        {
                            CategoryID = new Guid("0950f1d0-5c03-4f3a-9015-c4bb3c0e7620"),
                            CategoryName = "Cultural Understanding"
                        },
                        new
                        {
                            CategoryID = new Guid("3ce7d7d2-176d-4b72-8d98-4b97b49ed0c1"),
                            CategoryName = "Resilience and Adaptability"
                        });
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.CommentVote", b =>
                {
                    b.Property<Guid>("VoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VoteValue")
                        .HasColumnType("int");

                    b.HasKey("VoteID");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CommentID");

                    b.HasIndex("UserID");

                    b.ToTable("CommentVotes", "comments");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.Issue", b =>
                {
                    b.Property<Guid>("IssueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlockedContentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentIssueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentSolutionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScopeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IssueID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("BlockedContentID");

                    b.HasIndex("ParentIssueID");

                    b.HasIndex("ParentSolutionID");

                    b.HasIndex("ScopeID");

                    b.ToTable("Issues", "issues");

                    b.HasData(
                        new
                        {
                            IssueID = new Guid("fd43657c-a0a8-4721-a6b5-3f23e35088fc"),
                            AuthorID = new Guid("1a61454c-5b83-4aab-8661-96d6dffbee30"),
                            Content = "A issue to discuss practical solutions to climate change at individual and policy levels.",
                            ContentStatus = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScopeID = new Guid("a1e7c6b3-d5e2-4f8a-9c3b-8d7e6f5d4c2b"),
                            Title = "Climate Change Solutions"
                        },
                        new
                        {
                            IssueID = new Guid("4aebb16c-b474-4c14-9e5e-4548134cadc8"),
                            AuthorID = new Guid("1a61454c-5b83-4aab-8661-96d6dffbee30"),
                            Content = "Discussion on modern urban planning approaches for sustainable and livable cities.",
                            ContentStatus = 1,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScopeID = new Guid("b2d8f1a7-e4c9-4f8a-8d5f-7e6c9d8b3a2f"),
                            Title = "Urban Planning Innovations"
                        },
                        new
                        {
                            IssueID = new Guid("c246d67c-427c-40f9-8bb2-b0834e473f7b"),
                            AuthorID = new Guid("1a61454c-5b83-4aab-8661-96d6dffbee31"),
                            Content = "Strategies for transitioning to renewable energy sources at community and national levels.",
                            ContentStatus = 1,
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentIssueID = new Guid("fd43657c-a0a8-4721-a6b5-3f23e35088fc"),
                            ScopeID = new Guid("a1e7c6b3-d5e2-4f8a-9c3b-8d7e6f5d4c2b"),
                            Title = "Renewable Energy Transition"
                        },
                        new
                        {
                            IssueID = new Guid("b3a72e5d-7c18-4e9f-8d24-67a2c6f35b1d"),
                            AuthorID = new Guid("1a61454c-5b83-4aab-8661-96d6dffbee31"),
                            Content = "The world is experiencing a biodiversity crisis, with thousands of species teetering on the edge of extinction.",
                            ContentStatus = 1,
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScopeID = new Guid("a1e7c6b3-d5e2-4f8a-9c3b-8d7e6f5d4c2b"),
                            Title = "Critical Decline of Endangered Species"
                        },
                        new
                        {
                            IssueID = new Guid("e5d8f6a9-3b7c-42e1-9d85-7f63a4b5c28d"),
                            AuthorID = new Guid("1a61454c-5b83-4aab-8661-96d6dffbee31"),
                            Content = "The Southern Resident orca population has dropped from 88 individuals in 2010 to just 74 as of late 2024. This decline is attributed to a combination of factors, including reduced prey availability, pollution, and vessel traffic.",
                            ContentStatus = 1,
                            CreatedAt = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentIssueID = new Guid("b3a72e5d-7c18-4e9f-8d24-67a2c6f35b1d"),
                            ScopeID = new Guid("b2d8f1a7-e4c9-4f8a-8d5f-7e6c9d8b3a2f"),
                            Title = "Decline of the Southern Resident orca population"
                        });
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.IssueCategory", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IssueID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryID", "IssueID");

                    b.HasIndex("IssueID");

                    b.ToTable("IssuesCategories", "issues");

                    b.HasData(
                        new
                        {
                            CategoryID = new Guid("81f910e0-39a4-4b44-88ca-fd3c30af4a25"),
                            IssueID = new Guid("fd43657c-a0a8-4721-a6b5-3f23e35088fc")
                        },
                        new
                        {
                            CategoryID = new Guid("25487e1f-b167-4666-a20c-dec2e4b5f413"),
                            IssueID = new Guid("fd43657c-a0a8-4721-a6b5-3f23e35088fc")
                        },
                        new
                        {
                            CategoryID = new Guid("3ce7d7d2-176d-4b72-8d98-4b97b49ed0c1"),
                            IssueID = new Guid("fd43657c-a0a8-4721-a6b5-3f23e35088fc")
                        },
                        new
                        {
                            CategoryID = new Guid("25487e1f-b167-4666-a20c-dec2e4b5f413"),
                            IssueID = new Guid("4aebb16c-b474-4c14-9e5e-4548134cadc8")
                        },
                        new
                        {
                            CategoryID = new Guid("f5c35e6a-8c4f-4556-b6c1-4448b26d1bcb"),
                            IssueID = new Guid("4aebb16c-b474-4c14-9e5e-4548134cadc8")
                        },
                        new
                        {
                            CategoryID = new Guid("26c867f2-48c6-4bd5-b36a-9f7325431ad3"),
                            IssueID = new Guid("4aebb16c-b474-4c14-9e5e-4548134cadc8")
                        },
                        new
                        {
                            CategoryID = new Guid("81f910e0-39a4-4b44-88ca-fd3c30af4a25"),
                            IssueID = new Guid("c246d67c-427c-40f9-8bb2-b0834e473f7b")
                        },
                        new
                        {
                            CategoryID = new Guid("25487e1f-b167-4666-a20c-dec2e4b5f413"),
                            IssueID = new Guid("c246d67c-427c-40f9-8bb2-b0834e473f7b")
                        },
                        new
                        {
                            CategoryID = new Guid("f5c35e6a-8c4f-4556-b6c1-4448b26d1bcb"),
                            IssueID = new Guid("c246d67c-427c-40f9-8bb2-b0834e473f7b")
                        });
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.IssueVote", b =>
                {
                    b.Property<Guid>("VoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IssueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VoteValue")
                        .HasColumnType("int");

                    b.HasKey("VoteID");

                    b.HasIndex("AppUserId");

                    b.HasIndex("IssueID");

                    b.HasIndex("UserID");

                    b.ToTable("IssueVotes", "issues");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.Scope", b =>
                {
                    b.Property<Guid>("ScopeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScopeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScopeID");

                    b.ToTable("Scopes", "app");

                    b.HasData(
                        new
                        {
                            ScopeID = new Guid("a1e7c6b3-d5e2-4f8a-9c3b-8d7e6f5d4c2b"),
                            ScopeName = "Global"
                        },
                        new
                        {
                            ScopeID = new Guid("b2d8f1a7-e4c9-4f8a-8d5f-7e6c9d8b3a2f"),
                            ScopeName = "National"
                        },
                        new
                        {
                            ScopeID = new Guid("c3b9a2d8-f1e7-4f8a-9c3b-8d7e6f5d4c2b"),
                            ScopeName = "Local"
                        },
                        new
                        {
                            ScopeID = new Guid("d4c9b3a2-f8e7-4f8a-9c3b-8d7e6f5d4c2b"),
                            ScopeName = "Individual"
                        });
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.Solution", b =>
                {
                    b.Property<Guid>("SolutionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlockedContentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IssueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ScopeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("SolutionID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("BlockedContentID");

                    b.HasIndex("IssueID");

                    b.HasIndex("ScopeID");

                    b.ToTable("Solutions", "solutions");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.SolutionCategory", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SolutionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryID", "SolutionID");

                    b.HasIndex("SolutionID");

                    b.ToTable("SolutionsCategories", "solutions");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.SolutionVote", b =>
                {
                    b.Property<Guid>("VoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SolutionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VoteValue")
                        .HasColumnType("int");

                    b.HasKey("VoteID");

                    b.HasIndex("AppUserId");

                    b.HasIndex("SolutionID");

                    b.HasIndex("UserID");

                    b.ToTable("SolutionVotes", "solutions");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.UserComment", b =>
                {
                    b.Property<Guid>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlockedContentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("ContentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IssueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentCommentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SolutionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("BlockedContentID");

                    b.HasIndex("IssueID");

                    b.HasIndex("ParentCommentID");

                    b.HasIndex("SolutionID");

                    b.ToTable("Comments", "comments");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.UserHistory", b =>
                {
                    b.Property<Guid>("UserHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CommentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IssueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("SolutionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserVoteID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserHistoryID");

                    b.HasIndex("CommentID");

                    b.HasIndex("IssueID");

                    b.HasIndex("SolutionID");

                    b.HasIndex("UserID");

                    b.ToTable("UserHistory", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.CommentVote", b =>
                {
                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", null)
                        .WithMany("CommentVotes")
                        .HasForeignKey("AppUserId");

                    b.HasOne("atlas_the_public_think_tank.Models.UserComment", "Comment")
                        .WithMany("CommentVotes")
                        .HasForeignKey("CommentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.Issue", b =>
                {
                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", "Author")
                        .WithMany("Issues")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("atlas_the_public_think_tank.Models.BlockedContent", "BlockedContent")
                        .WithMany("Issues")
                        .HasForeignKey("BlockedContentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("atlas_the_public_think_tank.Models.Issue", "ParentIssue")
                        .WithMany("ChildIssues")
                        .HasForeignKey("ParentIssueID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("atlas_the_public_think_tank.Models.Solution", "ParentSolution")
                        .WithMany("ChildIssues")
                        .HasForeignKey("ParentSolutionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("atlas_the_public_think_tank.Models.Scope", "Scope")
                        .WithMany("Issues")
                        .HasForeignKey("ScopeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("BlockedContent");

                    b.Navigation("ParentIssue");

                    b.Navigation("ParentSolution");

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.IssueCategory", b =>
                {
                    b.HasOne("atlas_the_public_think_tank.Models.Category", "Category")
                        .WithMany("IssueCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("atlas_the_public_think_tank.Models.Issue", "Issue")
                        .WithMany("IssueCategories")
                        .HasForeignKey("IssueID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.IssueVote", b =>
                {
                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", null)
                        .WithMany("IssueVotes")
                        .HasForeignKey("AppUserId");

                    b.HasOne("atlas_the_public_think_tank.Models.Issue", "Issue")
                        .WithMany("IssueVotes")
                        .HasForeignKey("IssueID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.Solution", b =>
                {
                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", "Author")
                        .WithMany("Solutions")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("atlas_the_public_think_tank.Models.BlockedContent", "BlockedContent")
                        .WithMany("Solutions")
                        .HasForeignKey("BlockedContentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("atlas_the_public_think_tank.Models.Issue", "Issue")
                        .WithMany("Solutions")
                        .HasForeignKey("IssueID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("atlas_the_public_think_tank.Models.Scope", "Scope")
                        .WithMany()
                        .HasForeignKey("ScopeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("BlockedContent");

                    b.Navigation("Issue");

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.SolutionCategory", b =>
                {
                    b.HasOne("atlas_the_public_think_tank.Models.Category", "Category")
                        .WithMany("SolutionCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("atlas_the_public_think_tank.Models.Solution", "Solution")
                        .WithMany("SolutionCategories")
                        .HasForeignKey("SolutionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.SolutionVote", b =>
                {
                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", null)
                        .WithMany("SolutionVotes")
                        .HasForeignKey("AppUserId");

                    b.HasOne("atlas_the_public_think_tank.Models.Solution", "Solution")
                        .WithMany("SolutionVotes")
                        .HasForeignKey("SolutionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.UserComment", b =>
                {
                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("atlas_the_public_think_tank.Models.BlockedContent", "BlockedContent")
                        .WithMany("Comments")
                        .HasForeignKey("BlockedContentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("atlas_the_public_think_tank.Models.Issue", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("IssueID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("atlas_the_public_think_tank.Models.UserComment", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("ParentCommentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("atlas_the_public_think_tank.Models.Solution", "Solution")
                        .WithMany("Comments")
                        .HasForeignKey("SolutionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("BlockedContent");

                    b.Navigation("Issue");

                    b.Navigation("ParentComment");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.UserHistory", b =>
                {
                    b.HasOne("atlas_the_public_think_tank.Models.UserComment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("atlas_the_public_think_tank.Models.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("atlas_the_public_think_tank.Models.Solution", "Solution")
                        .WithMany()
                        .HasForeignKey("SolutionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("atlas_the_public_think_tank.Models.AppUser", "User")
                        .WithMany("UserHistory")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Issue");

                    b.Navigation("Solution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.AppUser", b =>
                {
                    b.Navigation("CommentVotes");

                    b.Navigation("Comments");

                    b.Navigation("IssueVotes");

                    b.Navigation("Issues");

                    b.Navigation("SolutionVotes");

                    b.Navigation("Solutions");

                    b.Navigation("UserHistory");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.BlockedContent", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Issues");

                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.Category", b =>
                {
                    b.Navigation("IssueCategories");

                    b.Navigation("SolutionCategories");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.Issue", b =>
                {
                    b.Navigation("ChildIssues");

                    b.Navigation("Comments");

                    b.Navigation("IssueCategories");

                    b.Navigation("IssueVotes");

                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.Scope", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.Solution", b =>
                {
                    b.Navigation("ChildIssues");

                    b.Navigation("Comments");

                    b.Navigation("SolutionCategories");

                    b.Navigation("SolutionVotes");
                });

            modelBuilder.Entity("atlas_the_public_think_tank.Models.UserComment", b =>
                {
                    b.Navigation("ChildComments");

                    b.Navigation("CommentVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
