// <auto-generated />
using System;
using Atlas.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atlas.Persistence.Migrations
{
    [DbContext(typeof(AtlasDataContext))]
    [Migration("20260930213148_AddIdentityAccounts")]
    partial class AddIdentityAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Atlas.Persistence.BlockRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Markdown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlockRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.CommentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AuthorParticipantId")
                        .HasDatabaseName("IX_CommentRows_AuthorParticipantId");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("IX_CommentRows_ParentCommentId");

                    b.ToTable("CommentRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.CommunityMembershipRow", b =>
                {
                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CommunityId", "ParticipantId");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("IX_CommunityMembershipRows_ParticipantId");

                    b.ToTable("CommunityMembershipRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.CommunityNodeRow", b =>
                {
                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssociatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("AssociatedByParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommunityId", "NodeId");

                    b.HasIndex("AssociatedByParticipantId")
                        .HasDatabaseName("IX_CommunityNodeRows_AssociatedByParticipantId");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("IX_CommunityNodeRows_NodeId");

                    b.ToTable("CommunityNodeRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.CommunityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("OwnerParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Community_Name");

                    b.HasIndex("OwnerParticipantId")
                        .HasDatabaseName("IX_CommunityRows_OwnerParticipantId");

                    b.ToTable("CommunityRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.DeliveryAttemptRow", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("NotificationId", "Position");

                    b.ToTable("NotificationDeliveryAttempts", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.DocumentBlockRow", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentId", "Position");

                    b.HasIndex("BlockId")
                        .HasDatabaseName("IX_DocumentBlocks_BlockId");

                    b.ToTable("DocumentBlocks", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.DocumentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("DocumentRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.Identity.AtlasIdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("Atlas.Persistence.ModerationCaseRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PublicReason")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RestorationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RestoredBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReviewRequestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("VisibilityRestoredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("IX_ModerationCaseRows_NodeId");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("IX_ModerationCaseRows_ReporterId");

                    b.HasIndex("RestoredBy")
                        .HasDatabaseName("IX_ModerationCaseRows_RestoredBy");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("IX_ModerationCaseRows_ReviewerId");

                    b.ToTable("ModerationCaseRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.NodeParentRow", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ParentNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NodeId", "Position");

                    b.HasIndex("ParentNodeId")
                        .HasDatabaseName("IX_NodeParents_ParentNodeId");

                    b.ToTable("NodeParents", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.NodeReactionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppliedByParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReactionDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AppliedByParticipantId")
                        .HasDatabaseName("IX_NodeReactionRows_AppliedByParticipantId");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("IX_NodeReactionRows_NodeId");

                    b.HasIndex("ReactionDefinitionId")
                        .HasDatabaseName("IX_NodeReactionRows_ReactionDefinitionId");

                    b.ToTable("NodeReactionRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.NodeRequestedTypeRow", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NodeId", "Position");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("IX_NodeRequestedTypes_TypeId");

                    b.ToTable("NodeRequestedTypes", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.NodeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_NodeRows_AuthorId");

                    b.HasIndex("DescriptionId")
                        .HasDatabaseName("IX_NodeRows_DescriptionId");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("IX_NodeRows_TypeId");

                    b.ToTable("NodeRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.NodeTypeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AutoPluralize")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("NodeTypeRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.NotificationPreferencesRow", b =>
                {
                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DiscussionEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("DiscussionInApp")
                        .HasColumnType("bit");

                    b.Property<bool>("DiscussionPush")
                        .HasColumnType("bit");

                    b.Property<bool>("ModerationEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("ModerationInApp")
                        .HasColumnType("bit");

                    b.Property<bool>("ModerationPush")
                        .HasColumnType("bit");

                    b.HasKey("ParticipantId");

                    b.ToTable("NotificationPreferencesRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.NotificationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DismissedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("InAppVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecipientParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActorParticipantId")
                        .HasDatabaseName("IX_NotificationRows_ActorParticipantId");

                    b.HasIndex("RecipientParticipantId")
                        .HasDatabaseName("IX_NotificationRows_RecipientParticipantId");

                    b.HasIndex("OccurrenceId", "RecipientParticipantId")
                        .IsUnique()
                        .HasDatabaseName("IX_Notification_UniqueOccurrenceRecipient");

                    b.ToTable("NotificationRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.ParticipantRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ParticipantRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.ReactionAuditRow", b =>
                {
                    b.Property<Guid>("NodeReactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ActorParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RelatedNodeReactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NodeReactionId", "Position");

                    b.HasIndex("ActorParticipantId")
                        .HasDatabaseName("IX_ReactionAuditEntries_ActorParticipantId");

                    b.HasIndex("RelatedNodeReactionId")
                        .HasDatabaseName("IX_ReactionAuditEntries_RelatedNodeReactionId");

                    b.ToTable("ReactionAuditEntries", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.ReactionDefinitionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByParticipantId")
                        .HasDatabaseName("IX_ReactionDefinitionRows_CreatedByParticipantId");

                    b.ToTable("ReactionDefinitionRows", (string)null);
                });

            modelBuilder.Entity("Atlas.Persistence.VoteRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("IX_VoteRows_ParticipantId");

                    b.HasIndex("ParticipantId", "TargetType", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("IX_Vote_UniqueParticipantTarget");

                    b.ToTable("VoteRows", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94000000-0000-4000-8000-000000000001"),
                            ConcurrencyStamp = "94000000-0000-4000-8000-000000000001",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        },
                        new
                        {
                            Id = new Guid("94000000-0000-4000-8000-000000000002"),
                            ConcurrencyStamp = "94000000-0000-4000-8000-000000000002",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = new Guid("94000000-0000-4000-8000-000000000003"),
                            ConcurrencyStamp = "94000000-0000-4000-8000-000000000003",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "identity");
                });

            modelBuilder.Entity("Atlas.Persistence.CommentRow", b =>
                {
                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("AuthorParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CommentRows_ParticipantRows_AuthorParticipantId");

                    b.HasOne("Atlas.Persistence.CommentRow", null)
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_CommentRows_CommentRows_ParentCommentId");
                });

            modelBuilder.Entity("Atlas.Persistence.CommunityMembershipRow", b =>
                {
                    b.HasOne("Atlas.Persistence.CommunityRow", null)
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CommunityMembershipRows_CommunityRows_CommunityId");

                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CommunityMembershipRows_ParticipantRows_ParticipantId");
                });

            modelBuilder.Entity("Atlas.Persistence.CommunityNodeRow", b =>
                {
                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("AssociatedByParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CommunityNodeRows_ParticipantRows_AssociatedByParticipantId");

                    b.HasOne("Atlas.Persistence.CommunityRow", null)
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CommunityNodeRows_CommunityRows_CommunityId");

                    b.HasOne("Atlas.Persistence.NodeRow", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CommunityNodeRows_NodeRows_NodeId");
                });

            modelBuilder.Entity("Atlas.Persistence.CommunityRow", b =>
                {
                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("OwnerParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CommunityRows_ParticipantRows_OwnerParticipantId");
                });

            modelBuilder.Entity("Atlas.Persistence.DeliveryAttemptRow", b =>
                {
                    b.HasOne("Atlas.Persistence.NotificationRow", null)
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Persistence.DocumentBlockRow", b =>
                {
                    b.HasOne("Atlas.Persistence.BlockRow", null)
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentBlocks_BlockRows_BlockId");

                    b.HasOne("Atlas.Persistence.DocumentRow", null)
                        .WithMany("Blocks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Persistence.Identity.AtlasIdentityUser", b =>
                {
                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithOne()
                        .HasForeignKey("Atlas.Persistence.Identity.AtlasIdentityUser", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Persistence.ModerationCaseRow", b =>
                {
                    b.HasOne("Atlas.Persistence.NodeRow", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ModerationCaseRows_NodeRows_NodeId");

                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ModerationCaseRows_ParticipantRows_ReporterId");

                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("RestoredBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ModerationCaseRows_ParticipantRows_RestoredBy");

                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ModerationCaseRows_ParticipantRows_ReviewerId");
                });

            modelBuilder.Entity("Atlas.Persistence.NodeParentRow", b =>
                {
                    b.HasOne("Atlas.Persistence.NodeRow", null)
                        .WithMany("Parents")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.Persistence.NodeRow", null)
                        .WithMany()
                        .HasForeignKey("ParentNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_NodeParents_NodeRows_ParentNodeId");
                });

            modelBuilder.Entity("Atlas.Persistence.NodeReactionRow", b =>
                {
                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("AppliedByParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_NodeReactionRows_ParticipantRows_AppliedByParticipantId");

                    b.HasOne("Atlas.Persistence.NodeRow", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_NodeReactionRows_NodeRows_NodeId");

                    b.HasOne("Atlas.Persistence.ReactionDefinitionRow", null)
                        .WithMany()
                        .HasForeignKey("ReactionDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_NodeReactionRows_ReactionDefinitionRows_ReactionDefinitionId");
                });

            modelBuilder.Entity("Atlas.Persistence.NodeRequestedTypeRow", b =>
                {
                    b.HasOne("Atlas.Persistence.NodeRow", null)
                        .WithMany("RequestedTypes")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.Persistence.NodeTypeRow", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_NodeRequestedTypes_NodeTypeRows_TypeId");
                });

            modelBuilder.Entity("Atlas.Persistence.NodeRow", b =>
                {
                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_NodeRows_ParticipantRows_AuthorId");

                    b.HasOne("Atlas.Persistence.DocumentRow", null)
                        .WithMany()
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_NodeRows_DocumentRows_DescriptionId");

                    b.HasOne("Atlas.Persistence.NodeTypeRow", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_NodeRows_NodeTypeRows_TypeId");
                });

            modelBuilder.Entity("Atlas.Persistence.NotificationPreferencesRow", b =>
                {
                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_NotificationPreferencesRows_ParticipantRows_ParticipantId");
                });

            modelBuilder.Entity("Atlas.Persistence.NotificationRow", b =>
                {
                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("ActorParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_NotificationRows_ParticipantRows_ActorParticipantId");

                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("RecipientParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_NotificationRows_ParticipantRows_RecipientParticipantId");
                });

            modelBuilder.Entity("Atlas.Persistence.ReactionAuditRow", b =>
                {
                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("ActorParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ReactionAuditEntries_ParticipantRows_ActorParticipantId");

                    b.HasOne("Atlas.Persistence.NodeReactionRow", null)
                        .WithMany("AuditHistory")
                        .HasForeignKey("NodeReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.Persistence.NodeReactionRow", null)
                        .WithMany()
                        .HasForeignKey("RelatedNodeReactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ReactionAuditEntries_NodeReactionRows_RelatedNodeReactionId");
                });

            modelBuilder.Entity("Atlas.Persistence.ReactionDefinitionRow", b =>
                {
                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("CreatedByParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ReactionDefinitionRows_ParticipantRows_CreatedByParticipantId");
                });

            modelBuilder.Entity("Atlas.Persistence.VoteRow", b =>
                {
                    b.HasOne("Atlas.Persistence.ParticipantRow", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_VoteRows_ParticipantRows_ParticipantId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Atlas.Persistence.Identity.AtlasIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Atlas.Persistence.Identity.AtlasIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.Persistence.Identity.AtlasIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Atlas.Persistence.Identity.AtlasIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Persistence.DocumentRow", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("Atlas.Persistence.NodeReactionRow", b =>
                {
                    b.Navigation("AuditHistory");
                });

            modelBuilder.Entity("Atlas.Persistence.NodeRow", b =>
                {
                    b.Navigation("Parents");

                    b.Navigation("RequestedTypes");
                });

            modelBuilder.Entity("Atlas.Persistence.NotificationRow", b =>
                {
                    b.Navigation("DeliveryAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
