# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:       # Trigger on any push to any branch
    branches: ["*"]  # Wildcard to match any branch
  pull_request:  # Trigger on any pull request to any branch
    branches: ["*"]  # Wildcard to match any branch

jobs:
  E2E_Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore CloudTests/CloudTests.csproj
    - name: Build
      run: dotnet build CloudTests/CloudTests.csproj --no-restore
    - name: Test
      run: dotnet test CloudTests/CloudTests.csproj --no-build --verbosity normal